const express= require('express')
const route = express.Router()
const {signupController,LoginController} =require('../controller/auth')
const aboutController=require('../controller/about')
const {verifyToken} =require('../middleware/verifyMiddleware')
const sliderController=require('../controller/slider')
const {feedbackPostController,feedbackGetController,feedbackEmpController}=require('../controller/feedback')
const {replyPostController,replyViewController,replyGetController}=require('../controller/reply')
const {contactController}=require('../controller/contact')
const upload=require('../middleware/adminMiddle')
const {employeeGetController,empIdGetController}=require('../controller/employee')

console.log("Route...auth")
route.post('/signup',signupController)
route.post('/login',LoginController)
route.get('/about',verifyToken,aboutController)
route.get('/slider',verifyToken,sliderController)
route.post('/feedbackPost',feedbackPostController)
route.get('/feedbackGet',verifyToken,feedbackGetController)
route.post('/replyPost',replyPostController)
route.get('/replyGet',verifyToken,replyGetController)
route.get('/replyView',verifyToken,replyViewController)
route.get('/feedbackEmpId',verifyToken,feedbackEmpController)
route.post('/contact',upload.single('resume'),contactController)
route.get('/employeeGet',employeeGetController)
route.get('/empData',empIdGetController)

module.exports=route